from pydantic import BaseModel, Field
from typing import List


class LLMFeedback(BaseModel):
    attractiveness_score: int = Field(..., ge=0, le=100, description="The final attractiveness score from 0 to 100.")
    ai_suggestions: List[str] = Field(..., min_length=5, max_length=5, description="A list of exactly 5 concise, actionable suggestions for improvement.")


class ObjectAnalysis(BaseModel):
    label: str
    confidence: float
    bbox: List[int]  # [x1, y1, x2, y2]
    contrast_score_vs_bg: float  # Critical: Weber contrast ratio vs background


class AnalysisResult(BaseModel):
    # Core Metrics
    average_brightness: float
    contrast_level: float
    dominant_colors: List[str]
    word_count: int
    text_content: str
    
    # DL/CV Metrics
    face_count: int
    detected_emotion: str
    detected_objects: List[ObjectAnalysis]
    
    # Final Output (Generated by LLM)
    attractiveness_score: int
    ai_suggestions: List[str]
